### ISSUE TITLE
Adding of poetry installation instructions

### ISSUE THREAD

**Issue by tjdodwell** [digiLab-ai/DaFT#3]
README needs poetry installation instructions.

Happy to do this if it helps but @mikkelbue you might want to do this.

**Comment by mikkelbue** [comment]
@tjdodwell Happy for you to do this :)

**Comment by mikkelbue** [comment]
Closing as added in https://github.com/digiLab-ai/DaFT/commit/244af624f9f3627242480038f04ee27866c939c8
