### ISSUE TITLE
Could DaFT.run() return indices as well?

### ISSUE THREAD

**Issue by tjdodwell** [digiLab-ai/DaFT#4]
Currently `self.ga.run()` returns indices, the values of inputs are returned. Would be nice to be able to get the indices as well as optional return value.

Again happy to do this.

**Comment by mikkelbue** [comment]
I think that's a sensible idea. I would just
`return self.X[indices, :], indices`

**Comment by mikkelbue** [comment]
Closing as fixed in https://github.com/digiLab-ai/DaFT/pull/5
